### ISSUE TITLE
Documentation for Field and Textfield doesn't load

### ISSUE THREAD

**Issue by chaitanyah** [AdobeDocs/experience-manager-64.en#120]
Issue in ./help/sites-developing/xtypes.md

**Comment by anujkapo** [comment]
Thanks, @chaitanyah. We will fix it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17208.

**Comment by bohnertchris** [comment]
Regrettably this is a known issue due to a legacy documentation platform still being used for this legacy content. For this reason we cannot expect a fix.

We can offer the workaround of accessing the 6.1 version, as the Widgets-API has not changed since then. The link is:

https://experienceleague.adobe.com/docs/experience-manager-release-information/aem-release-updates/previous-updates/aem-previous-versions.html

Apologies for the inconvenience and hope this will help.
