### ISSUE TITLE
Provide details on how fields with <Mixed Entries> can be editable

### ISSUE THREAD

**Issue by Vishawdhaliwal** [AdobeDocs/experience-manager-64.en#129]
Issue in ./help/sites-authoring/editing-page-properties.md

When initializing a bulk edit, fields that contain different values and have the <Mixed Entries> placeholder are disabled. Multi-value fields should be editable even if their values don't exactly match up, and one should act with care when editing them.

The <Mixed Entries>  fields become editable if we deselect one of the pages and reselect it again.

**Comment by bohnertchris** [comment]
Hello @Vishawdhaliwal. Thank you for taking time to create an issue. However this sounds like a bug report since you are reporting seeing behavior different than expected in AEM. This is a repository for issues with the documentation. Please consider creating a customer care issue to report an issue with AEM itself.

https://helpx.adobe.com/contact/enterprise-support.ec.html

**Comment by aheim0** [comment]
Assume a support issue has been raised, so closing this issue.
