### ISSUE TITLE
why pause is used where is document

### ISSUE THREAD

**Issue by vgajend** [AdobeDocs/experience-manager-64.en#85]
Issue in help/sites-deploying/replication.md

why pause is used here and how it work. i dont see document on it.

**Comment by bohnertchris** [comment]
Hello @vgajend. Thank you for creating an issue.

Pause is not normally used in a typical workflow. It is useful when troubleshooting replication, which is why its usage is documented in Troubleshooting Replication [1], which is linked from the page in question under the Additional Resources heading.

If you have further suggestions of how to improve the documentation, please feel free to open another issue.

[1] https://docs.adobe.com/content/help/en/experience-manager-64/deploying/configuring/troubleshoot-rep.html#pausing-replication-agent-queue
